lib: extend rte_ipv6_frag_get_ipv6_fragment_header()
cjdoucette/dpdk pull request #1
Opened 2018-05-03 13:38 UTC by cjdoucette

2018-05-03 18:07 UTC, cjdoucette commented
@AltraMayor this pull request is ready for a review.

2018-05-04 14:21 UTC, AltraMayor requested changes
**lib: extend rte_ipv6_frag_get_ipv6_fragment_header()**

2018-05-04 14:21 UTC, AltraMayor commented on lib/librte_ip_frag/rte_ip_frag.h
> +			break;
Could you check that DPDK coding style requires this `break`? If not, we should drop it.

The same goes for `case IPPROTO_FRAGMENT:`.

2018-05-04 14:21 UTC, AltraMayor commented on lib/librte_ip_frag/rte_ip_frag.h
> +			((const uint8_t *)hdr + start);
We are not checking that `hp` is still pointing to valid memory. This is critical because a malicious packet could make `hp` invalid.

By the way, what does `hp` stand for?

2018-05-04 14:21 UTC, AltraMayor commented on lib/librte_ip_frag/rte_ip_frag.h
> +		start += hdrlen;
`hdrlen` is only used to update `start` AND `start` is only used to index `hdr`  AND `hdr` is only moves forward. So we can drop `hdrlen` and `start` and just keep updating `hdr` as needed.

2018-05-04 14:24 UTC, AltraMayor commented
1. You can add me as a second reviewer:
`Reviewed-by: Michel Machado <michel@digirati.com.br>`

2. Add the RFC reference and explains why this patch is needed to the patch message. This will help in the review process upstream.

2018-06-07 20:16 UTC, closed without merging