lib: add iterator over lpm rules
cjdoucette/dpdk pull request #4
Opened 2018-06-14 07:04 UTC by mengxiang0811

Add an iterator over the LPM rule entries.
The iterator requires a prefix as a parameter and
lists all entries as long as the given prefix (or longer).

Signed-off-by: Qiaobin Fu <qiaobinf@bu.edu>
Reviewed-by: Cody Doucette <doucette@bu.edu>
Reviewed-by: Michel Machado <michel@digirati.com.br>

2018-06-22 14:31 UTC, AltraMayor reviewed
**lib: add iterator over lpm rules**

Capitalize LPM in the title: **lib: add iterator over LPM rules**

Replace "rule entries"  with "rules" in the first sentence: Add an iterator over the LPM rules.

2018-06-23 16:47 UTC, AltraMayor requested changes
**lib: add iterator over lpm rules**

2018-06-23 16:47 UTC, AltraMayor commented on lib/librte_lpm/rte_lpm6.c
> +		mask_ip(state->ip_masked, state->depth);
Bug: `state->depth` has not been initialized at this point.

2018-06-23 16:47 UTC, AltraMayor commented on lib/librte_lpm/rte_lpm6.h
> + *   ip == NULL as having an all-zero IPv6 address
Improved sentence:
`ip == NULL behaves as having passed an all-zero IPv6 address`

2018-06-23 16:47 UTC, AltraMayor commented on lib/librte_lpm/rte_lpm6.c
> +	return -ENOENT;
Update `state->next` after leaving the `while` loop: `state->next = index;`

2018-06-23 20:04 UTC, mengxiang0811 commented
This patch is ready for another review.

2018-06-28 18:26 UTC, AltraMayor requested changes
**lib: add iterator over LPM rules**

Once addressed my tiny comment below, this patch is ready to go upstream.

Good luck!

2018-06-28 18:26 UTC, AltraMayor commented on lib/librte_lpm/rte_lpm6.c
> +		memset(state->ip_masked, 0, sizeof(state->ip_masked));
Isn't there `rte_memset()`?

2018-06-29 06:33 UTC, mengxiang0811 commented on lib/librte_lpm/rte_lpm6.c
> +		memset(state->ip_masked, 0, sizeof(state->ip_masked));
It seems there is no such a function call.

2018-06-29 15:49 UTC, AltraMayor commented on lib/librte_lpm/rte_lpm6.c
> +		memset(state->ip_masked, 0, sizeof(state->ip_masked));
Fine.

2018-10-28 19:46 UTC, closed without merging